"""Q4 evaluation: run every scenario in real time, then write the reports.

Produces two files, both generated from actual runs rather than written by hand:

* evaluation/latency_report.md          - P50/P95 end to end and per component
* evaluation/false_positive_analysis.md - scored against each scenario's
                                          declared ground truth, including the
                                          negative test where the correct
                                          behaviour is to stay quiet

Scoring uses the `expected_nudges` / `must_not_nudge` / `max_nudges` fields that
each scenario declares next to its script, so the ground truth is written before
the run rather than fitted to the result afterwards.
"""
from __future__ import annotations

import argparse
import asyncio
import json
import statistics
from datetime import datetime, timezone
from pathlib import Path

from ..common.config import EVAL_DIR, settings
from ..common.latency import LatencyCollector
from ..common.logging import log
from .pipeline import analyse_file


def _truth(scenario_id: str) -> dict | None:
    path = settings.recordings_dir / (scenario_id + ".truth.json")
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def score(report: dict, truth: dict) -> dict:
    fired = [n["kind"] for n in report["nudges"]]
    fired_set = set(fired)
    expected = set(truth.get("expected_nudges") or [])
    forbidden = set(truth.get("must_not_nudge") or [])
    max_nudges = truth.get("max_nudges")

    hits = sorted(expected & fired_set)
    missed = sorted(expected - fired_set)
    forbidden_fired = sorted(forbidden & fired_set)
    unexpected = sorted(fired_set - expected - forbidden)

    over_cap = (max_nudges is not None and len(fired) > max_nudges)
    passed = not missed and not forbidden_fired and not over_cap

    return {
        "scenario": truth["id"],
        "description": truth["description"],
        "seconds": truth["seconds"],
        "expected": sorted(expected),
        "fired": fired,
        "detected": hits,
        "missed": missed,
        "forbidden_fired": forbidden_fired,
        "unexpected": unexpected,
        "max_nudges": max_nudges,
        "over_cap": over_cap,
        "pass": passed,
        "suppression": report["suppression"],
    }


async def run_all(scenario_ids: list[str] | None = None, *, speed: float = 1.0,
                  use_llm: bool = True) -> dict:
    recordings = settings.recordings_dir
    ids = scenario_ids or sorted(
        p.stem.replace(".truth", "") for p in recordings.glob("q4_*.truth.json")
    )
    results: list[dict] = []
    combined = LatencyCollector()
    reports: dict[str, dict] = {}

    for sid in ids:
        wav = recordings / (sid + ".wav")
        truth = _truth(sid)
        if not wav.exists() or truth is None:
            log("eval.skip", scenario=sid, reason="missing wav or truth")
            continue
        log("eval.run", scenario=sid, seconds=truth["seconds"])
        report = await analyse_file(wav, call_id=sid, speed=speed, use_llm=use_llm)
        reports[sid] = report
        results.append(score(report, truth))
        for stage in report["latency"]:
            combined.samples.setdefault(stage, [])
        await asyncio.sleep(1.0)

    # aggregate raw samples properly by re-reading the saved per-call reports
    for sid, report in reports.items():
        for stage, stats in report["latency"].items():
            # `summary()` loses the raw samples, so approximate the distribution
            # with the recorded percentiles weighted by n. Documented honestly:
            # the per-scenario tables are exact, the combined table is pooled.
            combined.samples[stage].extend(
                [stats["p50_ms"]] * max(1, stats["n"] // 2)
                + [stats["p95_ms"]] * max(1, stats["n"] // 4)
                + [stats["min_ms"], stats["max_ms"]]
            )

    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "speed": speed,
        "llm_layer": use_llm,
        "scenarios": results,
        "per_scenario_latency": {sid: r["latency"] for sid, r in reports.items()},
        "pooled_latency": combined.summary(),
        "reports": reports,
    }
    EVAL_DIR.mkdir(parents=True, exist_ok=True)
    (EVAL_DIR / "q4_results.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    write_latency_report(payload)
    write_false_positive_report(payload)
    return payload


# --------------------------------------------------------------------------
def write_latency_report(payload: dict) -> Path:
    lines: list[str] = []
    add = lines.append
    add("# Q4 - Latency report")
    add("")
    add("Generated by `python -m darwix.realtime.evaluate` on "
        + payload["generated_at"][:19].replace("T", " ") + " UTC.")
    add("")
    add("Every number here comes from a run where the recording was replayed at "
        "**true real-time speed** (`speed=" + str(payload["speed"]) + "`). "
        "A 60-second call takes 60 seconds to analyse, so the pipeline never "
        "sees audio before it would exist on a live call.")
    add("")
    add("## What is being measured")
    add("")
    add("| Stage | Definition |")
    add("|---|---|")
    add("| `asr_ms` | Last audio sample of an utterance arrives -> transcript text available |")
    add("| `signal_rules_ms` | Deterministic detectors over the new transcript segment |")
    add("| `signal_llm_ms` | Rolling-window LLM analysis (runs debounced and concurrently) |")
    add("| `delivery_ms` | Nudge handed to the delivery sink (WebSocket / CLI) |")
    add("| `end_to_end_ms` | **Audio arrives -> nudge delivered.** The number that matters. |")
    add("")

    for sid, latency in payload["per_scenario_latency"].items():
        add("## " + sid)
        add("")
        add("| Stage | n | p50 (ms) | p95 (ms) | max (ms) |")
        add("|---|---:|---:|---:|---:|")
        for stage in ("asr_ms", "signal_rules_ms", "signal_llm_ms", "delivery_ms", "end_to_end_ms"):
            st = latency.get(stage)
            if not st:
                continue
            add("| `" + stage + "` | " + str(st["n"]) + " | " + str(st["p50_ms"])
                + " | " + str(st["p95_ms"]) + " | " + str(st["max_ms"]) + " |")
        add("")

    add("## Pooled across scenarios")
    add("")
    add("Pooled from the per-scenario distributions (the per-scenario tables above "
        "are exact; this one is a weighted pooling and is indicative).")
    add("")
    add("| Stage | p50 (ms) | p95 (ms) |")
    add("|---|---:|---:|")
    for stage, st in payload["pooled_latency"].items():
        add("| `" + stage + "` | " + str(st["p50_ms"]) + " | " + str(st["p95_ms"]) + " |")
    add("")
    add("## Reading these numbers")
    add("")
    add("- **ASR dominates.** It is a network call to a hosted Whisper endpoint; "
        "everything after it is local and costs single-digit milliseconds, except "
        "the LLM layer.")
    add("- **The rules layer is effectively free**, which is why every "
        "compliance-critical signal is detected there and never depends on a model "
        "call that might time out.")
    add("- **The LLM layer runs concurrently and debounced**, so its latency adds to "
        "its own nudges but never delays transcription or a compliance alert.")
    add("- **End to end is dominated by how long the speaker talks**, not by the "
        "pipeline: a segment is only transcribed once the utterance ends. That is a "
        "deliberate accuracy/latency trade and is discussed in "
        "`docs/limitations_and_production_plan.md`.")
    add("")
    path = EVAL_DIR / "latency_report.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    log("eval.latency_report", path=str(path))
    return path


def write_false_positive_report(payload: dict) -> Path:
    lines: list[str] = []
    add = lines.append
    add("# Q4 - False-positive control and nudge quality")
    add("")
    add("Generated by `python -m darwix.realtime.evaluate` on "
        + payload["generated_at"][:19].replace("T", " ") + " UTC.")
    add("")
    add("Each scenario declares its expected nudges, its forbidden nudges and a cap "
        "**before** it is run (`data/recordings/<id>.truth.json`, written from the "
        "scenario script). Results are scored against that, not fitted to it.")
    add("")
    add("## Results")
    add("")
    add("| Scenario | Expected | Detected | Missed | Forbidden fired | Other | Verdict |")
    add("|---|---|---|---|---|---|---|")
    for r in payload["scenarios"]:
        add("| `" + r["scenario"] + "` | " + (", ".join(r["expected"]) or "_none_")
            + " | " + (", ".join(r["detected"]) or "-")
            + " | " + (", ".join(r["missed"]) or "-")
            + " | " + (", ".join(r["forbidden_fired"]) or "-")
            + " | " + (", ".join(r["unexpected"]) or "-")
            + " | " + ("PASS" if r["pass"] else "FAIL") + " |")
    add("")

    add("## Suppression")
    add("")
    add("| Scenario | Signals considered | Nudges shown | Below threshold | Duplicate | Cooldown | Suppression rate |")
    add("|---|---:|---:|---:|---:|---:|---:|")
    for r in payload["scenarios"]:
        s = r["suppression"]
        add("| `" + r["scenario"] + "` | " + str(s["signals_considered"]) + " | "
            + str(s["emitted"]) + " | " + str(s["suppressed_below_threshold"]) + " | "
            + str(s["suppressed_duplicate"]) + " | " + str(s["suppressed_cooldown"]) + " | "
            + str(s["suppression_rate_pct"]) + "% |")
    add("")

    total_fired = sum(len(r["fired"]) for r in payload["scenarios"])
    total_unexpected = sum(len(r["unexpected"]) + len(r["forbidden_fired"])
                           for r in payload["scenarios"])
    rate = round(100.0 * total_unexpected / max(1, total_fired), 1)
    add("## Approximate false-positive rate")
    add("")
    add("**" + str(total_unexpected) + " of " + str(total_fired) + " nudges ("
        + str(rate) + "%) were not in the scenario's expected set.**")
    add("")
    add("This is an upper bound, and deliberately unflattering: anything not named "
        "in the expected list counts against the system, including nudges that were "
        "arguably useful but simply not anticipated when the scenario was written. "
        "A per-nudge judgement is in the notes below.")
    add("")
    add("## Notes on individual results")
    add("")
    for r in payload["scenarios"]:
        add("### `" + r["scenario"] + "`")
        add("")
        add(r["description"].strip())
        add("")
        if r["missed"]:
            add("- **Missed:** " + ", ".join(r["missed"]) + ".")
        if r["forbidden_fired"]:
            add("- **Fired something forbidden:** " + ", ".join(r["forbidden_fired"]) + ".")
        if r["unexpected"]:
            add("- **Unanticipated:** " + ", ".join(r["unexpected"])
                + ". Counted as a false positive by the rate above.")
        if r["over_cap"]:
            add("- **Over the cap:** " + str(len(r["fired"])) + " nudges against a cap of "
                + str(r["max_nudges"]) + ".")
        if r["pass"] and not r["unexpected"]:
            add("- Clean pass.")
        add("")
    path = EVAL_DIR / "false_positive_analysis.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    log("eval.fp_report", path=str(path))
    return path


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="Run the Q4 scenarios and write the reports")
    ap.add_argument("scenarios", nargs="*")
    ap.add_argument("--speed", type=float, default=1.0)
    ap.add_argument("--no-llm", action="store_true")
    args = ap.parse_args()

    payload = asyncio.run(run_all(args.scenarios or None, speed=args.speed,
                                  use_llm=not args.no_llm))
    print()
    for r in payload["scenarios"]:
        print(("PASS " if r["pass"] else "FAIL ") + r["scenario"]
              + "  fired=" + ",".join(r["fired"] or ["-"]))
    e2e = payload["pooled_latency"].get("end_to_end_ms", {})
    if e2e:
        print("\nend-to-end p50", e2e["p50_ms"], "ms | p95", e2e["p95_ms"], "ms")
